// Generated by CoffeeScript 1.3.3

  var attributes, audio, dataRef, fragments, iframe, index, page, reset, sendHTML, sendJS, setFragment, video;

  attributes = function(attr) {
    var key, value;
    return ((function() {
      var _results;
      _results = [];
      for (key in attr) {
        value = attr[key];
        _results.push("" + key + "=" + value);
      }
      return _results;
    })()).join(" ");
  };

  audio = function(url, attr) {
    if (attr == null) {
      attr = {
        autoplay: true
      };
    }
    return "<audio " + (attributes(attr)) + ">        <source src='" + url + "'/>     </audio>";
  };

  video = function(url, attr) {
    if (attr == null) {
      attr = {
        autoplay: true
      };
    }
    return "<video " + (attributes(attr)) + ">        <source src='" + url + "'/>     </video>";
  };
  
  image = function(url, attr) {
    if (attr == null) {
      attr = {
        src: url
      }
    }
    return "<img src='" + url + "'/>";
  }

  iframe = function(url) {
    return "<iframe src='" + url + "' width='99%' height='99%'/>";
  };

  sendPage = function(url) {
    var k = "dafuq";
    $.get('pages/' + url + '.html', function (res) { sendHTML(res); })
  };

  sendHTML = function(html) {
    return dataRef.set({
      type: 'html',
      value: html
    });
  };

  sendJS = function(js) {
    return dataRef.set({
      type: 'js',
      value: js
    });
  };
  
  sendCSS = function(map) {
    return dataRef.set({
      type: 'css',
      value: map
    })
  }

  index = -1;

  dataRef = new Firebase('http://gamma.firebase.com/broadway/');

  fragments = [];

  fragments.push("Presentations are boring.<br>" + image('http://www.wonderbranding.com/wp-content/uploads/2012/05/boring.gif'))
  
  fragments.push("Broadway is not!");
  
  fragments = fragments.concat(['We aim to give people a new,', 'real time medium...']);
  
  fragments.push("The web. " + image('http://tgstax.com/documents/searchology-web-graph.png'))
  
  fragments.push("It's real time.");
  
  fragments = fragments.concat("I can push every single word I say.".split(" "))
  
  fragments.push("I can show you");
  
  fragments.push(iframe("http://www.highcharts.com/demo/"))
  
  fragments.push("or")
  
  fragments.push(iframe("http://upload.wikimedia.org/wikipedia/commons/e/e6/Merge_sort_algorithm_diagram.svg"))
  
  fragments.push("I can improv.");
  
  fragments.push("So we can have a little less qqq");
  
  fragments.push("And a little more pew pew pew!");
  

  //fragments.push(audio("http://noproblo.dayjo.org/ZeldaSounds/LOZ/LOZ_Shield.wav") + "Beep.");

  reset = function() {
    index = -1;
    return sendHTML("Please wait...");
  };

  setFragment = function(idx) {
    var frag;
    index = idx;
    if (index < fragments.length) {
      frag = fragments[index];
      return sendHTML(frag);
    } else if(index >= fragments.length) {
      return sendHTML("Curtains drop.");
    } else {
      reset();
    }
  };
  
  nextFragment = function() {
    setFragment(index + 1);
  }
  
  prevFragment = function() {
    setFragment(index - 1);
  }

  $(document).ready(function() {
    $(document).keyup(function(event) {
      console.log(event);
      if (event.which === 39) {
        nextFragment();
      } else if(event.which == 37) {
        prevFragment();
      }
    });
    return reset();
  });